### ISSUE TITLE
For downloading file for windows

### ISSUE THREAD

**Issue by JmaireInra** [heaslon/Easy-Leaf-Area#1]
Dear, I'm trying to use this fantastic app on his Windows version and unfortunately it's impossible  to find the file LeafArea.exe or LeafArea.py. Can you help me?
Regards

**Comment by heaslon** [comment]
Both files are in EasyLeafArea.zip.  
https://github.com/heaslon/Easy-Leaf-Area/blob/master/EasyLeafArea.zip
Click view the full file to download the '.zip'
