### ISSUE TITLE
Picture resizing

### ISSUE THREAD

**Issue by vetchj88** [heaslon/Easy-Leaf-Area#2]
When I open a jpeg in EasyLeaf it often cuts out a decent portion of the picture... sometimes this is resolved if the image is "flipped" or "Rotated" but mostly those options have no effect... I have tried resizing photos but that also is hit and miss. Are there any standard sizes that easyleaf recognizes or how else might i fix the issue? And thanks a ton for making the software!

**Comment by heaslon** [comment]
Even if part of the photo appears cut off,  Easy Leaf Area should still process the entire image.  You should see this if you look at the saved output jpeg.  What size (pixels x pixels) photos are you using?  For leaf area measurement you can usually use lower resolutions (800x600) unless your leaves are really small in your pictures.

**Comment by vetchj88** [comment]
Thank you very much, I appreciate the quick feedback. The pictures are 2975x4094... I am measuring the area of wheat heads so I thought a higher resolution would be necessary because of all the detail. And after looking at the saved jpegs EasyLeaf is indeed measuring the entire image. Thanks again!
